### ISSUE TITLE
problems: No errors or warnings

### ISSUE THREAD

**Issue by unional** [grafana/vscode-jsonnet#7]
When I open a file, e.g. `qa.jsonnet`, it adds a entry in the Problems panel saying "No Errors or warnings"

Is this expected? thx

**Comment by julienduchesne** [comment]
Hey, it's expected but not ideal. When I last tested this, sending no diagnostics didn't clear previous errors, so I added this info: https://github.com/grafana/jsonnet-language-server/blob/fa0afc7ebea6462d3083342e4ba61918044ce303/pkg/server/diagnostics.go#L79-L87 to the language server so that errors would be cleared when resolved

I'm due to revisit this, other language servers do not have this issue so there must be something I'm doing wrong. I'll look into it 👀

**Comment by julienduchesne** [comment]
Should be fixed with https://github.com/grafana/jsonnet-language-server/releases/tag/v0.7.2
